server:
  port: 8082
  servlet:
    context-path: /blog
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    name: ys_blog
    url: jdbc:mysql://47.115.188.221:3306/ys_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      filters: stat
      max-active: 10
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      async-init: true
      validation-query: select 1


  # redis
  redis:
    database: 0
    host: 47.115.188.221
    port: 6379
    password: 123456
  # 配置jackson 时间返回格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis-plus 配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:mapping/**/**.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.frame.**.entity
  #刷新mapper 调试神器
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增"
      #INPUT:"用户输入ID",
      #ID_WORKER:"全局唯一ID (数字类型唯一ID)",
      #UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: IGNORED
      #驼峰下划线转换

  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，
    #自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    com.ysmork.blog.dao: debug
  config: classpath:logback-spring.xml



token:
  secret: c83adb0b44eb4692
  header: Token
  expireTime: 30


